Fix pid_t / db_threadid_t has not been declared windows build error.
Also removed FORTIFY_SOURCE to fix undefined reference to `__memcpy_chk' windows build error.